# Generated by Django 6.1.1 on 2026-10-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_movimentacaocaixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaocaixa',
            options={},
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='caixa.caixa'),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo',
            field=models.CharField(choices=[('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria')], max_length=12),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
