# Generated by Django 6.1.1 on 2026-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_alter_movimentacaocaixa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='observacao_fechamento',
            field=models.TextField(blank=True),
        ),
    ]
